##POR
server:
  port: ${APP_PORT:8083}

spring:
  application:
    name: inventory-service

  ## mysql connection
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:ticket-booking-db}?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver


  ## jpa properties
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

jwt:
  token:
    secret : 5367566859703373367639792F423F452848284D6251655468576D5A71347437

services:
  event:
    baseUrl: ${EVENT_SERVICE_URL:http://localhost:8081}
  venue:
    baseUrl: ${VENUE_SERVICE_URL:http://localhost:8082}

kafka:
  bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
  consumer:
    inv-service-group: inv-service-group
  topics:
    event-instance-create: event-instance-create